# Generated by Django 5.2.15 on 2026-08-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back1', '0004_remove_booking_user_name_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
    ]
