# Generated by Django 5.2.15 on 2026-08-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back1', '0005_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
