# Generated by Django 5.2.15 on 2026-08-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back1', '0007_emergency_booking_actual_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='gate_type',
            field=models.CharField(choices=[('entrance', 'Entrance'), ('exit', 'Exit')], default='entrance', max_length=20),
        ),
    ]
