# Generated by Django 5.2.15 on 2026-08-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back1', '0008_gate_gate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
