# Generated by Django 5.2.15 on 2026-08-09 22:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def initialise_phase1_foundation(apps, schema_editor):
    ParkingSlot = apps.get_model('back1', 'ParkingSlot')
    SensorData = apps.get_model('back1', 'SensorData')
    Transaction = apps.get_model('back1', 'Transaction')
    ParkingRate = apps.get_model('back1', 'ParkingRate')

    for slot_number in ('A01', 'A02', 'A03', 'A04', 'A05', 'A06'):
        ParkingSlot.objects.get_or_create(
            slot_number=slot_number,
            defaults={'status': 'available'},
        )

    for slot in ParkingSlot.objects.all():
        slot.is_enabled = slot.status != 'disabled'
        slot.is_physically_occupied = slot.status == 'occupied'
        slot.is_under_maintenance = slot.status == 'maintenance'
        slot.is_backup = slot.status == 'backup'
        slot.is_booking_reserved = slot.status == 'reserved'
        slot.save(update_fields=[
            'is_enabled',
            'is_physically_occupied',
            'is_under_maintenance',
            'is_backup',
            'is_booking_reserved',
        ])

    for sensor in SensorData.objects.all():
        if sensor.status == 'inactive':
            sensor.connection_status = 'offline'
        elif sensor.status == 'error':
            sensor.connection_status = 'error'
            sensor.condition_status = 'abnormal'
        else:
            sensor.connection_status = 'online'
        sensor.last_reading_at = sensor.updated_at
        sensor.save(update_fields=[
            'connection_status',
            'condition_status',
            'last_reading_at',
        ])

    for payment in Transaction.objects.all():
        if payment.transaction_type == 'penalty':
            payment.payment_category = 'overstay'
        elif payment.transaction_type == 'refund':
            payment.payment_category = 'refund'
        else:
            payment.payment_category = 'normal'
        payment.payment_status = 'paid'
        payment.paid_at = payment.created_at
        payment.save(update_fields=[
            'payment_category',
            'payment_status',
            'paid_at',
        ])

    if not ParkingRate.objects.exists():
        ParkingRate.objects.create(
            rate_per_hour='2.00',
            overtime_rate_per_hour='20.00',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('back1', '0010_seed_default_gates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='normal_parking_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('outstanding', 'Outstanding')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_booking_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_physically_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_under_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='condition_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='connection_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='last_reading_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='back1.booking'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_category',
            field=models.CharField(choices=[('normal', 'Normal Parking Payment'), ('overstay', 'Overstay Payment'), ('wallet_top_up', 'Wallet Top Up'), ('refund', 'Refund')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('outstanding', 'Outstanding')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('parked', 'Parked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('no_show', 'No Show'), ('overtime', 'Overtime')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='gate',
            name='gate_type',
            field=models.CharField(choices=[('entrance', 'Entrance'), ('exit', 'Exit')], default='entrance', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled'), ('backup', 'Backup / Admin Reserved')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('entrance', 'Entrance Vehicle Sensor'), ('exit', 'Exit Vehicle Sensor'), ('parking', 'Parking Space Sensor'), ('emergency', 'Emergency Sensor'), ('car', 'Car Detection'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('fire', 'Fire Detection')], max_length=20),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sensor_abnormal', 'Sensor Abnormal'), ('sensor_offline', 'Sensor Offline'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='back1.sensordata')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='back1.emergency')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notifications', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emergency_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('vehicle_detected', 'Vehicle Detected'), ('gate_opened', 'Gate Opened'), ('gate_closed', 'Gate Closed'), ('space_occupied', 'Parking Space Occupied'), ('space_available', 'Parking Space Available'), ('sensor_offline', 'Sensor Offline'), ('sensor_online', 'Sensor Online'), ('emergency', 'Emergency'), ('admin_action', 'Admin Action'), ('payment', 'Payment'), ('other', 'Other')], default='other', max_length=30)),
                ('source', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to='back1.booking')),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to='back1.gate')),
                ('parking_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to='back1.parkingslot')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to='back1.sensordata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            initialise_phase1_foundation,
            migrations.RunPython.noop,
        ),
    ]
