# Generated by Django 5.2.15 on 2026-08-09 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back1', '0011_phase1_model_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pending_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_category', 'normal'), ('payment_status', 'paid'), ('transaction_type', 'payment')), fields=('booking',), name='one_paid_normal_transaction_per_booking'),
        ),
    ]
