# Generated by Django 5.2.15 on 2026-08-09 23:05

from django.conf import settings
from django.db import migrations, models


def seed_logical_sensors(apps, schema_editor):
    SensorData = apps.get_model("back1", "SensorData")
    ParkingSlot = apps.get_model("back1", "ParkingSlot")
    definitions = [
        ("ENTRANCE_01", "entrance", "Entrance Gate", None),
        ("EXIT_01", "exit", "Exit Gate", None),
        ("EMERGENCY_01", "emergency", "Emergency", None),
    ] + [
        (f"PARK_A0{i}", "parking", f"Parking A0{i}", f"A0{i}")
        for i in range(1, 7)
    ]
    for sensor_id, sensor_type, location, slot_number in definitions:
        slot = ParkingSlot.objects.filter(slot_number=slot_number).first() if slot_number else None
        SensorData.objects.update_or_create(
            sensor_id=sensor_id,
            defaults={
                "sensor_type": sensor_type,
                "location": location,
                "parking_slot": slot,
                "value": "clear",
                "status": "active",
                "connection_status": "offline",
                "condition_status": "normal",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('back1', '0012_part_a_booking_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='entrance_gate_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='exit_gate_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_category', 'overstay'), ('payment_status', 'paid'), ('transaction_type', 'penalty')), fields=('booking',), name='one_paid_overstay_transaction_per_booking'),
        ),
        migrations.RunPython(seed_logical_sensors, migrations.RunPython.noop),
    ]
