# Generated by Django 5.2.15 on 2026-08-10 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back1', '0014_part_c_alert_acknowledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_category', 'refund'), ('payment_status', 'paid'), ('transaction_type', 'refund')), fields=('booking',), name='one_paid_normal_refund_per_booking'),
        ),
    ]
