# Generated by Django 5.2.15 on 2026-08-12 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back1', '0015_booking_refund_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(db_index=True, max_length=50)),
                ('sensor_type', models.CharField(choices=[('entrance', 'Entrance Vehicle Sensor'), ('exit', 'Exit Vehicle Sensor'), ('parking', 'Parking Space Sensor'), ('emergency', 'Emergency Sensor'), ('car', 'Car Detection'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('fire', 'Fire Detection')], max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('condition_status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='normal', max_length=20)),
                ('connection_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='online', max_length=20)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
    ]
