# Generated by Django 5.2.15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back1", "0017_gatecommand_gate_is_physically_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("vehicle_detected", "Vehicle Detected"),
                    ("gate_opened", "Gate Opened"),
                    ("gate_closed", "Gate Closed"),
                    ("space_occupied", "Parking Space Occupied"),
                    ("space_available", "Parking Space Available"),
                    ("led_turned_on", "LED Turned On"),
                    ("led_turned_off", "LED Turned Off"),
                    ("sensor_offline", "Sensor Offline"),
                    ("sensor_online", "Sensor Online"),
                    ("emergency", "Emergency"),
                    ("admin_action", "Admin Action"),
                    ("payment", "Payment"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),

        migrations.CreateModel(
            name="ParkingLED",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "led_name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("on", "On"),
                        ],
                        default="off",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "parking_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leds",
                        to="back1.parkingslot",
                    ),
                ),
            ],
            options={
                "ordering": ["parking_slot", "led_name"],
            },
        ),

        migrations.CreateModel(
            name="LEDCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("on", "On"),
                            ("off", "Off"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executing", "Executing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "requested_via",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                            ("lifecycle", "Lifecycle"),
                        ],
                        default="admin",
                        max_length=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "parking_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_commands",
                        to="back1.parkingslot",
                    ),
                ),
                (
                    "led",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="back1.parkingled",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),

        migrations.AddConstraint(
            model_name="ledcommand",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    status__in=["pending", "executing"]
                ),
                fields=("led", "action"),
                name="one_unresolved_led_action",
            ),
        ),
    ]